/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2016-04-14 17:01:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t\t<meta charset=\"utf-8\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, minimal-ui\">\n");
      out.write("\t\t<title>Peri Peri, About Us</title>\n");
      out.write("\n");
      out.write("\t<link href=\"favicon.png\" type=\"image/x-icon\" rel=\"shortcut icon\">\n");
      out.write("\t\t<link href=\"assets/css/master.css\" rel=\"stylesheet\">\n");
      out.write("\t\t<script src=\"assets/plugins/jquery/jquery-1.11.3.min.js\"></script>\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\n");
      out.write("\t\t<!-- Loader -->\n");
      out.write("\t\t<div id=\"page-preloader\"><span class=\"spinner\"></span></div>\n");
      out.write("\t\t<!-- Loader end -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"layout-theme animated-css\" id=\"wrapper\" data-header=\"sticky\" data-header-top=\"200\">\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"sb-site\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"wrap-content\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- HEADER -->\n");
      out.write("\t\t\t\t\t<header class=\"header clearfix\">\n");
      out.write("\t\t\t\t\t\t<div class=\"header__wrap\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sb-toggle-left\"><i class=\"icon pe-7s-menu\"></i></span>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"logo\" href=\"http://localhost:8080/Pizza/\"><img class=\"img-responsive\" src=\"assets/img/logo_mod-a.png\" alt=\"Logo\"></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t<!-- end header -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"section-title\">\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"section__inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h1 class=\"ui-title-page\">About Us</h1>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ol class=\"breadcrumb\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"http://localhost:8080/Pizza/\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"active\">About Us</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- end section__inner -->\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- end row -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end container -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end section-title -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<section class=\"section_mod-j\">\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"ui-title-block\">We are pizza makers, and our mission is to make hot pizzas which feeds all your senses.</h2>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"advantages advantages_mod-a\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"advantages__item\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon pe-7s-leaf\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"advantages__title ui-title-inner\">We're Careful</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"advantages__description\">The crust is stored in a separate container, on a separate shelf in our fridge. The cheese, marinara sauce and pepperoni are stored in a  designated kit, and every pizza is freshly baked on designated parchment paper in our ovens.</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"advantages__item border-effect\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"border-effect__top\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"border-effect__right\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"border-effect__bottom\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"border-effect__left\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon pe-7s-medal\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"advantages__title ui-title-inner\">We're Certified</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"advantages__description\">Our pizzas are prepared using the procedures certified by the Food Safety and Standards Authority of India(FSSAI) and we take specific caution when making these pizzas.</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"advantages__item\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon pe-7s-rocket\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"advantages__title ui-title-inner\">We're flexible</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"advantages__description\">We understand that sometimes you may need a delivery at a particular time maybe to surprise a friend and hence we deliver pizza as per your said time if you mention it while placing the order. Also in case of bulk orders we give complementary pizzas depending on the amount of order received!</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- end advantages -->\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- end row -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end container -->\n");
      out.write("\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t<!-- end section-default -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<section class=\"section_mod-c\">\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- end row -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end container -->\n");
      out.write("\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t<!-- end section-default -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 class=\"ui-title-block\">Frequently Asked Questions</h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"ui-subtitle-block\">Here are the answers to the most common questions we receive.</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"accordion accordion_mod-b panel-group rtd\" id=\"accordion-1\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn-collapse\" data-toggle=\"collapse\" data-parent=\"#accordion-1\" href=\"#collapse-1\"><i class=\"icon icon_small\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title ui-title-inner ui-title-inner__small\">I can't find what I'm looking for.  Where can I go to ask my question?</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"collapse-1\" class=\"panel-collapse collapse in\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>You are free to contact us anytime you want. Drop in your query at the Contact Us page and we will try to answer your question as soon as possible. Happy to Help!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- end panel -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn-collapse collapsed\" data-toggle=\"collapse\" data-parent=\"#accordion-1\" href=\"#collapse-2\"><i class=\"icon icon_small\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title ui-title-inner ui-title-inner__small\">What is the minimum amount I have to order for delivery?</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"collapse-2\" class=\"panel-collapse collapse\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>The minimum order bill should be Rs.230 for free home delivery.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- end panel -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn-collapse collapsed\" data-toggle=\"collapse\" data-parent=\"#accordion-1\" href=\"#collapse-3\"><i class=\"icon icon_small\"></i></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title ui-title-inner ui-title-inner__small\">How long will my delivery take?</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"collapse-3\" class=\"panel-collapse collapse\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>We like to say deliveries take approximately 45 mins during weekdays and approximately 1 hour on weekends. We do our best to get your delicious pizza out to you as soon as possible (we know youâre craving it) but we like to give ourselves a little extra time in case our drivers encounter unforeseen circumstances, which may include traffic and bad weather. The most important thing to us is making sure our drivers arrive safely and that your pizza arrives hot!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- end panel -->\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- end accordion -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- end row -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end container -->\n");
      out.write("\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t<!-- end section-default -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<section class=\"section-subscribe\">\n");
      out.write("\t\t\t\t\t\t<form class=\"form-subscribe\" action=\"subscribe\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2 class=\"ui-title-block ui-title-block_mod-a form-subscribe__title\">Sign up for the newsletter and get exclusive deals.</h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"email\" placeholder=\"Enter your email address\" name=\"subscribe_email\" required>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"page\" value=\"about\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"ui-btn ui-btn_mod-c btn-effect btn-effect\" type=\"submit\">subscribe</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- end col -->\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end row -->\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- end container -->\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t<!-- end footer-form -->\n");
      out.write("\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t<!-- end section-subscribe -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<footer class=\"footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"copyright border-top\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">Copyright © 2016 <a class=\"copyright__link\" href=\"\">Peri Peri.</a> All rights reserved.</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div><!-- end copyright -->\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t\t<!-- end footer -->\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end wrap-content -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end #sb-site -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sb-slidebar sb-left\">\n");
      out.write("\t\t\t\t<nav class=\"main-nav\">\n");
      out.write("\t\t\t\t\t<ul class=\"navig-menu list-unstyled\">\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"http://localhost:8080/Pizza/\">Home</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"shop-catalog.jsp\">Pizza menu</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"about.jsp\">about us</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"contactus.jsp\">contact</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- end main-nav -->\n");
      out.write("\t\t\t\t<div class=\"border-bottom\"></div>\n");
      out.write("\t\t\t\t");

					String email = (String)session.getAttribute("email");
												
					if(email == null || email == "fail")
					{	session.setAttribute("email", null);
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<a class=\"link-account\" href=\"login-signup.jsp\">login</a>\n");
      out.write("\t\t\t\t\t");
}
					else
					{
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- <a class=\"link-account\" onclick=\"logout()\" href=\"http://localhost:8080/Pizza/\">log out</a> -->\n");
      out.write("\t\t\t\t\t\t<a class=\"link-account\" href=\"logout.jsp\">log out</a>\n");
      out.write("\t\t\t\t\t");
}
				
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end sb-left -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end layout-theme -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- SCRIPTS MAIN -->\n");
      out.write("\n");
      out.write("\t\t<script src=\"assets/js/jquery-migrate-1.2.1.js\"></script>\n");
      out.write("\t\t<script src=\"assets/plugins/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("\t\t<script src=\"assets/js/waypoints.min.js\"></script>\n");
      out.write("\t\t<script src=\"../../cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\n");
      out.write("\t\t<script src=\"assets/js/modernizr.custom.js\"></script>\n");
      out.write("\t\t<script src=\"assets/js/cssua.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!--SCRIPTS THEME-->\n");
      out.write("\n");
      out.write("\t\t<!-- Sidebar -->\n");
      out.write("\t\t<script src=\"assets/plugins/slidebars/dist/slidebars.js\"></script>\n");
      out.write("\t\t<!-- Home slider -->\n");
      out.write("\t\t<script src=\"assets/plugins/slider-pro/dist/js/jquery.sliderPro.js\"></script>\n");
      out.write("\t\t<!-- Sliders -->\n");
      out.write("\t\t<script src=\"assets/plugins/owl-carousel/owl.carousel.min.js\"></script>\n");
      out.write("\t\t<!-- Isotope -->\n");
      out.write("\t\t<script src=\"assets/plugins/isotope/isotope.pkgd.min.js\"></script>\n");
      out.write("\t\t<!-- Modal -->\n");
      out.write("\t\t<script src=\"assets/plugins/prettyphoto/js/jquery.prettyPhoto.js\"></script>\n");
      out.write("\t\t<!-- Date select -->\n");
      out.write("\t\t<script src=\"assets/plugins/datetimepicker/jquery.datetimepicker.js\"></script>\n");
      out.write("\t\t<!-- Select customization -->\n");
      out.write("\t\t<script src=\"assets/plugins/bootstrap-select/dist/js/bootstrap-select.min.js\"></script>\n");
      out.write("\t\t<!-- Price slider -->\n");
      out.write("\t\t<script src=\"assets/plugins/nouislider/jquery.nouislider.all.min.js\"></script>\n");
      out.write("\t\t<!-- Chart -->\n");
      out.write("\t\t<script src=\"assets/plugins/rendro-easy-pie-chart/dist/jquery.easypiechart.min.js\"></script>\n");
      out.write("\t\t<!-- Animation -->\n");
      out.write("\t\t<script src=\"assets/js/wow.min.js\"></script>\n");
      out.write("\t\t<!-- Scrollspy -->\n");
      out.write("\t\t<script src=\"assets/js/scrollspy.min.js\"></script>\n");
      out.write("\n");
      out.write("\t\t<!-- Custom -->\n");
      out.write("\t\t<script src=\"assets/js/custom.js\"></script>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
