/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2016-04-16 05:51:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_002dsignup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, minimal-ui\">\r\n");
      out.write("\t\t<title>Peri Peri, Log in / Sign up</title>\r\n");
      out.write("\r\n");
      out.write("    \t<link href=\"favicon.png\" type=\"image/x-icon\" rel=\"shortcut icon\">\r\n");
      out.write("\t\t<link href=\"assets/css/master.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<script src=\"assets/plugins/jquery/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction validate()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"postcodeerror\").style.visibility = \"hidden\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"post\").style.border=\"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"addre\").checked = true)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(isNaN(document.signupform.postcode.value) || document.signupform.postcode.value.length != 6)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tif(document.signupform.phone.value.length == 10)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"phoneno\").style.border=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"phoneerror\").style.visibility = \"hidden\";\r\n");
      out.write("\t\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"post\").style.border=\"1px solid #dd1037\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"postcodeerror\").style.visibility = \"visible\";\r\n");
      out.write("\t\t\t\t\t\tdocument.signupform.postcode.focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(isNaN(document.signupform.phone.value) || document.signupform.phone.value.length != 10)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"phoneno\").style.border=\"1px solid #dd1037\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"phoneerror\").style.visibility = \"visible\";\r\n");
      out.write("\t\t\t\t\t\tdocument.signupform.phone.focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"phoneno\").style.border=\"\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"phoneerror\").style.visibility = \"hidden\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(document.getElementById(\"pwd\").value.length < 6)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwderror\").innerHTML = \"Password must contain at least six characters\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwd\").style.border=\"1px solid #dd1037\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwderror\").style.visibility = \"visible\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tre = /[0-9]/;\r\n");
      out.write("\t\t\t\t\tif(!re.test(document.getElementById(\"pwd\").value))\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwderror\").innerHTML = \"Password must contain at least one digit\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwd\").style.border=\"1px solid #dd1037\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwderror\").style.visibility = \"visible\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tre = /[a-z]/;\r\n");
      out.write("\t\t\t\t\tif(!re.test(document.getElementById(\"pwd\").value))\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwderror\").innerHTML = \"Password must contain at least one lowercase letter\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwd\").style.border=\"1px solid #dd1037\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwderror\").style.visibility = \"visible\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tre = /[A-Z]/;\r\n");
      out.write("\t\t\t\t\tif(!re.test(document.getElementById(\"pwd\").value))\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwderror\").innerHTML = \"Password must contain at least one uppercase letter\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwd\").style.border=\"1px solid #dd1037\";\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"pwderror\").style.visibility = \"visible\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Loader -->\r\n");
      out.write("\t\t<div id=\"page-preloader\"><span class=\"spinner\"></span></div>\r\n");
      out.write("\t\t<!-- Loader end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"layout-theme animated-css\" id=\"wrapper\" data-header=\"sticky\" data-header-top=\"200\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"sb-site\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"wrap-content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- HEADER -->\r\n");
      out.write("\t\t\t\t\t<header class=\"header clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"header__wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sb-toggle-left\"><i class=\"icon pe-7s-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"logo\" href=\"http://localhost:8080/Pizza/\"><img class=\"img-responsive\" src=\"assets/img/logo_mod-a.png\" alt=\"Logo\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t<!-- end header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"section-title\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"section__inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h1 class=\"ui-title-page\">Log in / Sign up</h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"http://localhost:8080/Pizza/\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"active\">Login - Signup</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- end section__inner -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- end row -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- end container -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end section-title -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"section_mod-f\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <form class=\"comment-reply-form\" id=\"comment-reply-form\" action=\"#\" method=\"get\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- <form class=\"comment-reply-form\" id=\"comment-reply-form\" action=\"s\" method=\"post\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<section class=\"section-area\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<!-- Checkbox Selection -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\"#addre\").click(function () {\r\n");
      out.write("                if ($(this).is(\":checked\")) {\r\n");
      out.write("                    $(\"#dvPassport\").hide();\r\n");
      out.write("\t\t\t\t\t$(\"#dvPassportx\").show();\r\n");
      out.write("                } else {\r\n");
      out.write("                    $(\"#dvPassport\").show();\r\n");
      out.write("\t\t\t\t\t$(\"#dvPassportx\").hide();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<form class=\"comment-reply-form\" id=\"comment-reply-form\" action=\"login\" method=\"post\">\r\n");
      out.write("\t<div id=\"dvPassport\">\r\n");
      out.write("       \t\t\t\t\t\t\t\t\t\t\t<h2 class=\"ui-title-inner ui-title-inner_mod-a\">Login</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t ");
 String email = (String)session.getAttribute("email");
												if(email != "fail")
												{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">EMAIL ADDRESS *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"email\" name=\"uemail\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">PASSWORD *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"password\" name=\"upass\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
}
												else
												{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">EMAIL ADDRESS *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input style=\"border: 1px solid #dd1037;\" class=\"form-control\" type=\"email\" name=\"uemail\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">PASSWORD *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input style=\"border: 1px solid #dd1037;\" class=\"form-control\" type=\"password\" name=\"upass\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
}
												
												if(email == "fail")
												{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\" style=\"color:#dd1037;\">The email or password you have entered does not match.</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <button class=\"comment-reply-form__btn ui-btn ui-btn-primary btn-effect\" type=\"submit\">Login</button> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"comment-reply-form__btn ui-btn ui-btn-primary btn-effect\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("    </div>\r\n");
      out.write("\t<input class=\"forms__check hidden\" type=\"checkbox\" id=\"addre\"  value=\"\">\r\n");
      out.write("    <label class=\"forms__label forms__label-check forms__label-check_mod-a\" for=\"addre\">Not a member yet? Join Now.</label>\r\n");
      out.write("    <hr />\r\n");
      out.write("\t\t\t");

				String exist = (String)session.getAttribute("exist");
    			if(exist == "true")
    			{
      out.write("\r\n");
      out.write("    \t\t\t\t<div class=\"row\">\r\n");
      out.write("    \t\t\t\t<!-- <div class=\"col-md-6\" style=\"color:#D94F2B;\">email already exist</div> -->\r\n");
      out.write("    \t\t\t\t<h2 class=\"ui-title-inner ui-title-inner_mod-a\" style=\"color:#D94F2B;\">This email id already exists!</h2>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("    \t\t\t");
}
			
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"dvPassportx\" style=\"display: none\">\r\n");
      out.write("\t<form class=\"comment-reply-form\" name=\"signupform\" id=\"comment-reply-form\" action=\"signup\" method=\"post\" onsubmit=\"return validate()\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<h2 class=\"ui-title-inner ui-title-inner_mod-a\">Sign Up</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">FIRST NAME *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" name=\"fname\" required >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">LAST NAME *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" name=\"lname\" required >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">ADDRESS *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control form-control_second\" type=\"text\" placeholder=\"Street address\" name=\"street\"required >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" placeholder=\"Apartment, suite, unit etc.\" name=\"apartment\" required >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">TOWN / CITY *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" placeholder=\"Town / City\" name=\"town\" required >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">POSTCODE *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <input class=\"form-control\" type=\"text\" placeholder=\"Postcode / Zip\" name=\"postcode\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" name=\"postcode\" placeholder=\"Postcode / Zip\" id=\"post\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"postcode\" id=\"postcodeerror\" style=\"visibility: hidden; color: #dd1037;\"><b>Please provide valid postcode</b></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">PHONE *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <input class=\"form-control\" type=\"text\" name=\"phone\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" name=\"phone\" id=\"phoneno\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"phone\" id=\"phoneerror\" style=\"visibility: hidden; color: #dd1037;\"><b>Please provide valid phone</b></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">EMAIL ADDRESS *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"email\" name=\"email\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"ui-form-label\">PASSWORD *</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"password\" name=\"password\" id=\"pwd\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<b><label for=\"password\" id=\"pwderror\" style=\"visibility: hidden; color: #dd1037;\"></label></b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <button class=\"comment-reply-form__btn ui-btn ui-btn-primary btn-effect\" type=\"submit\">Signup</button> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"comment-reply-form__btn ui-btn ui-btn-primary btn-effect\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("</form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- </form> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- end section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"section-contact\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<section class=\"contact-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"contact-block__title ui-title-inner\">Get in Touch</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"contact-block__inner\">Phone: <span class=\"color_primary\">+91 9664356445 </span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"contact-block__inner\">Email: <span class=\"color_primary\">akkipatil1994@gmail.com</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"contact-block__inner\">Phone: <span class=\"color_primary\">+91 9870111444 </span></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"contact-block__inner\">Email: <span class=\"color_primary\">neerajmenon1412@gmail.com</span></div>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<section class=\"contact-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"contact-block__title ui-title-inner\">Store Address</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"contact-block__info\">Shankar Smurti Bldg </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"contact-block__inner\">Plot no.:506, Sec:22 </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"contact-block__inner\">Turbhe, Navi Mumbai</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- end row -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- end container -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end section_mod-b -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<section class=\"section-subscribe\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-subscribe\" action=\"subscribe\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h2 class=\"ui-title-block ui-title-block_mod-a form-subscribe__title\">Sign up for the newsletter and get exclusive deals.</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"email\" placeholder=\"Enter your email address\" name=\"subscribe_email\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"page\" value=\"lo-si\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"ui-btn ui-btn_mod-c btn-effect btn-effect\" type=\"submit\">subscribe</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- end col -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end row -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- end container -->\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<!-- end footer-form -->\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t<!-- end section-subscribe -->\t\t\r\n");
      out.write("\t\t\t\t\t<footer class=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"copyright border-top\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">Copyright © 2016 <a class=\"copyright__link\" href=\"\">Peri Peri.</a> All rights reserved.</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div><!-- end copyright -->\r\n");
      out.write("\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- end wrap-content -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end #sb-site -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"sb-slidebar sb-left\">\r\n");
      out.write("\t\t\t\t<nav class=\"main-nav\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navig-menu list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"http://localhost:8080/Pizza/\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"shop-catalog.jsp\">Pizza menu</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"about.html\">about us</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"contactus.jsp\">contact</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- end main-nav -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"border-bottom\"></div>\r\n");
      out.write("\t\t\t\t");

					if(email == null || email == "fail")
					{	session.setAttribute("email", null);
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a class=\"link-account\" href=\"login-signup.jsp\">login</a>\r\n");
      out.write("\t\t\t\t\t");
}
					else
					{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- <a class=\"link-account\" onclick=\"logout()\" href=\"http://localhost:8080/Pizza/\">log out</a> -->\r\n");
      out.write("\t\t\t\t\t\t<a class=\"link-account\" href=\"logout.jsp\">log out</a>\r\n");
      out.write("\t\t\t\t\t");
}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end sb-left -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end layout-theme -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- SCRIPTS MAIN -->\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"assets/js/jquery-migrate-1.2.1.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/plugins/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/waypoints.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"../../cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/modernizr.custom.js\"></script>\r\n");
      out.write("\t\t<script src=\"assets/js/cssua.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!--SCRIPTS THEME-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Sidebar -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/slidebars/dist/slidebars.js\"></script>\r\n");
      out.write("\t\t<!-- Home slider -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/slider-pro/dist/js/jquery.sliderPro.js\"></script>\r\n");
      out.write("\t\t<!-- Sliders -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\t\t<!-- Isotope -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/isotope/isotope.pkgd.min.js\"></script>\r\n");
      out.write("\t\t<!-- Modal -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/prettyphoto/js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("\t\t<!-- Date select -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/datetimepicker/jquery.datetimepicker.js\"></script>\r\n");
      out.write("\t\t<!-- Select customization -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/bootstrap-select/dist/js/bootstrap-select.js\"></script>\r\n");
      out.write("\t\t<!-- Price slider -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/nouislider/jquery.nouislider.all.min.js\"></script>\r\n");
      out.write("\t\t<!-- Chart -->\r\n");
      out.write("\t\t<script src=\"assets/plugins/rendro-easy-pie-chart/dist/jquery.easypiechart.min.js\"></script>\r\n");
      out.write("\t\t<!-- Animation -->\r\n");
      out.write("\t\t<script src=\"assets/js/wow.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Custom -->\r\n");
      out.write("\t\t<script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
