/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2016-04-14 17:54:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.catpages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _2Peri_002dPeri_002dChicken_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t\t<meta charset=\"utf-8\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, minimal-ui\">\n");
      out.write("\t\t<title>Peri Peri, Peri-Peri Chicken</title>\n");
      out.write("\n");
      out.write("\t<link href=\"favicon.png\" type=\"image/x-icon\" rel=\"shortcut icon\">\n");
      out.write("\t\t<link href=\"../assets/css/masterpizpag.css\" rel=\"stylesheet\">\n");
      out.write("\t\t<script src=\"../assets/plugins/jquery/jquery-1.11.3.min.js\"></script>\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\n");
      out.write("\t\t<!-- Loader -->\n");
      out.write("\t\t<div id=\"page-preloader\"><span class=\"spinner\"></span></div>\n");
      out.write("\t\t<!-- Loader end -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"layout-theme animated-css\" id=\"wrapper\" data-header=\"sticky\" data-header-top=\"200\">\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"sb-site\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"wrap-content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- HEADER -->\n");
      out.write("\t\t\t\t\t<header class=\"header clearfix\">\n");
      out.write("\t\t\t\t\t\t<div class=\"header__wrap\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sb-toggle-left\"><i class=\"icon pe-7s-menu\"></i></span>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"logo\" href=\"http://localhost:8080/Pizza/\"><img class=\"img-responsive\" src=\"../assets/img/logo_mod-a.png\" alt=\"Logo\"></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t<!-- end header -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"section-title\">\n");
      out.write("\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-545\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"section__inner\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h1 class=\"ui-title-page\">Peri-Peri Chicken</h1>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ol class=\"breadcrumb\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"http://localhost:8080/Pizza/\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"../shop-catalog.jsp\">Pizza Menu</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"active\">Peri-Peri Chicken</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- end section__inner -->\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- end col -->\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- end row -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end container -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end section-title -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<article class=\"post post_first text-center clearfix\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"entry-media\">\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img class=\"img-responsive\" src=\"img/e2.jpg\" height=\"600\" width=\"1100\">\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"entry-main\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"entry-header\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"entry-title ui-title-inner\">Boneless skinless chicken breasts pounded to a uniform thickness with Peri Peri Hot Marinade to give your taste buds a treat!</h2>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</article><!-- end post -->\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<article class=\"post post_mod-b clearfix\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\"><span class=\"panel-title__number\"></span>Different Crust's Size</h3><br><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"pizza-builder__radio-label\" for=\"pizza-size_9\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pizza-builder__radio-number pizza-builder__radio-number_9\"><span class=\"pizza-builder__radio-inner\">9\"</span></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pizza-builder__radio-title\">Small<br>Rs. 260</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"pizza-builder__radio-label\" for=\"pizza-size_14\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pizza-builder__radio-number pizza-builder__radio-number_14\"><span class=\"pizza-builder__radio-inner\">14\"</span></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pizza-builder__radio-title\">Medium<br>Rs. 360</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"pizza-builder__radio-label\" for=\"pizza-size_18\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pizza-builder__radio-number pizza-builder__radio-number_18\"><span class=\"pizza-builder__radio-inner\">18\"</span></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"pizza-builder__radio-title\">Large<br>Rs. 550</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\"><span class=\"panel-title__number\"></span>Ingredients</h3><br><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"entry-content\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Marinated Chicken Breast Fillets, Shallots, Roasted Capsicum, Caramelised Onions & Bocconcini on a Tomato base, topped with Peri-Peri sauce.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</article><!-- end post -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- end col -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- end row -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- end container -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<footer class=\"footer\">\n");
      out.write("\t\t\t\t\t\t<div class=\"copyright border-top\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-99\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">Copyright © 2016 <a class=\"copyright__link\" href=\"http://localhost:8080/Pizza/\">Peri Peri.</a> All rights reserved.</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div><!-- end copyright -->\n");
      out.write("\t\t\t\t\t</footer>\n");
      out.write("\t\t\t\t\t<!-- end footer -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- end wrap-content -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end #sb-site -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"sb-slidebar sb-left\">\n");
      out.write("\t\t\t\t<nav class=\"main-nav\">\n");
      out.write("\t\t\t\t\t<ul class=\"navig-menu list-unstyled\">\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"http://localhost:8080/Pizza/\">Home</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"../shop-catalog.jsp\">Pizza menu</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"../about.jsp\">about us</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"navig-menu__item\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"navig-menu__link\" href=\"../contactus.jsp\">contact</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- end main-nav -->\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"border-bottom\"></div>\n");
      out.write("\t\t\t\t");

					String email = (String)session.getAttribute("email");
												
					if(email == null || email == "fail")
					{	session.setAttribute("email", null);
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<a class=\"link-account\" href=\"../login-signup.jsp\">login</a>\n");
      out.write("\t\t\t\t\t");
}
					else
					{
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- <a class=\"link-account\" onclick=\"logout()\" href=\"http://localhost:8080/Pizza/\">log out</a> -->\n");
      out.write("\t\t\t\t\t\t<a class=\"link-account\" href=\"../logout.jsp\">log out</a>\n");
      out.write("\t\t\t\t\t");
}
				
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- end sb-left -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- end layout-theme -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- SCRIPTS MAIN -->\n");
      out.write("\n");
      out.write("\t\t<script src=\"../assets/js/jquery-migrate-1.2.1.js\"></script>\n");
      out.write("\t\t<script src=\"../assets/plugins/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("\t\t<script src=\"../assets/js/waypoints.min.js\"></script>\n");
      out.write("\t\t<script src=\"../../../cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\n");
      out.write("\t\t<script src=\"../assets/js/modernizr.custom.js\"></script>\n");
      out.write("\t\t<script src=\"../assets/js/cssua.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!--SCRIPTS THEME-->\n");
      out.write("\n");
      out.write("\t\t<!-- Sidebar -->\n");
      out.write("\t\t<script src=\"../assets/plugins/slidebars/dist/slidebars.js\"></script>\n");
      out.write("\t\t<!-- Custom -->\n");
      out.write("\t\t<script src=\"../assets/js/custom.js\"></script>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
